# Generated by Django 6.0.5 on 2026-06-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_reviews_notifications_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact',
        ),
    ]
