# Generated by Django 6.0.5 on 2026-06-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_remove_patientprofile_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
