# Generated by Django 6.0.5 on 2026-06-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_appointment_doctor'),
        ('Patient', '0004_appointment_payment_method'),
    ]

    operations = [
    ]
