# Generated by Django 6.0.5 on 2026-06-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('hospital_admin', 'Hospital Admin'), ('super_admin', 'Super Admin')], default='patient', max_length=20),
        ),
    ]
