# Generated by Django 6.0.5 on 2026-07-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
