# Generated by Django 6.0.5 on 2026-06-18 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('cancel', 'Cancel'), ('checkin', 'Check-In'), ('issue', 'Token Issue'), ('reception', 'Reception Action')], default='checkin', max_length=20)),
                ('related_token', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=20)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('visit_type', models.CharField(choices=[('Walk-In', 'Walk-In'), ('Booking', 'Booking'), ('Emergency', 'Emergency'), ('Follow-Up', 'Follow-Up')], default='Walk-In', max_length=20)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('arrived', 'Arrived'), ('serving', 'Serving'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancelled_at', models.TimeField(blank=True, null=True)),
                ('cancel_source', models.CharField(blank=True, choices=[('patient-app', 'Cancelled by Patient (App)'), ('receptionist', 'Cancelled by Receptionist')], max_length=20, null=True)),
                ('reassigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='admin_panel.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='reception.patient')),
            ],
            options={
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_prefix', models.CharField(db_index=True, max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('counter_value', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('doctor_prefix', 'date')},
            },
        ),
    ]
