# Generated by Django 6.0.5 on 2026-07-07 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def fix_duplicate_tokens(apps, schema_editor):
    QueueEntry = apps.get_model('reception', 'QueueEntry')
    TokenCounter = apps.get_model('reception', 'TokenCounter')
    from django.utils import timezone

    all_entries = QueueEntry.objects.all().order_by('created_at')
    seen_tokens = set()
    today = timezone.now().date()

    for entry in all_entries:
        if entry.token in seen_tokens:
            prefix = entry.token.split('-')[0]
            max_val = TokenCounter.objects.filter(
                doctor_prefix=prefix
            ).aggregate(max_val=Max('counter_value'))['max_val'] or 0
            new_counter = max_val + 1
            TokenCounter.objects.update_or_create(
                doctor_prefix=prefix,
                date=today,
                defaults={'counter_value': new_counter},
            )
            new_token = f"{prefix}-{new_counter}"
            QueueEntry.objects.filter(pk=entry.pk).update(token=new_token)
            seen_tokens.add(new_token)
        else:
            seen_tokens.add(entry.token)


class Migration(migrations.Migration):

    replaces = [('reception', '0001_initial'), ('reception', '0002_fix_duplicate_tokens'), ('reception', '0003_alter_queueentry_token'), ('reception', '0004_queueentry_scheduled_date')]

    dependencies = [
        ('hospital_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('cancel', 'Cancel'), ('checkin', 'Check-In'), ('issue', 'Token Issue'), ('reception', 'Reception Action')], default='checkin', max_length=20)),
                ('related_token', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=20)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('visit_type', models.CharField(choices=[('Walk-In', 'Walk-In'), ('Booking', 'Booking'), ('Emergency', 'Emergency'), ('Follow-Up', 'Follow-Up')], default='Walk-In', max_length=20)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('arrived', 'Arrived'), ('serving', 'Serving'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancelled_at', models.TimeField(blank=True, null=True)),
                ('cancel_source', models.CharField(blank=True, choices=[('patient-app', 'Cancelled by Patient (App)'), ('receptionist', 'Cancelled by Receptionist')], max_length=20, null=True)),
                ('reassigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='hospital_admin.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='reception.patient')),
            ],
            options={
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_prefix', models.CharField(db_index=True, max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('counter_value', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('doctor_prefix', 'date')},
            },
        ),
        migrations.RunPython(
            code=fix_duplicate_tokens,
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='token',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='For Booking type: the appointment date', null=True),
        ),
    ]
