# Generated by Django 6.0.5 on 2026-06-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_alter_queueentry_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='For Booking type: the appointment date', null=True),
        ),
    ]
