# Generated by Django 6.0.5 on 2026-06-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🏥', max_length=10)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('head', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('doctors_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('National Holiday', 'National Holiday'), ('State Holiday', 'State Holiday'), ('Hospital Closure', 'Hospital Closure'), ('Maintenance', 'Maintenance')], default='National Holiday', max_length=50)),
                ('affects_all', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='City Care Medical Centre', max_length=200)),
                ('address', models.TextField(blank=True, default='123, Health Nagar, Sector 7, Lucknow, UP — 226001')),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(blank=True, default='admin@citycaremc.com', max_length=254)),
                ('website', models.CharField(blank=True, default='www.citycaremc.com', max_length=200)),
                ('logo_icon', models.CharField(default='🏥', max_length=10)),
                ('registration_no', models.CharField(blank=True, default='#UPCM-2019-00427', max_length=100)),
                ('established', models.IntegerField(blank=True, default=2019, null=True)),
                ('bed_capacity', models.IntegerField(blank=True, default=120, null=True)),
                ('accreditation', models.CharField(blank=True, default='NABH Certified', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Profile',
                'verbose_name_plural': 'Hospital Profile',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar_color', models.CharField(default='av-1', max_length=20)),
                ('days_available', models.CharField(default='Mon–Fri', max_length=100)),
                ('morning_slots', models.CharField(blank=True, help_text='e.g. 09:00–13:00', max_length=100)),
                ('evening_slots', models.CharField(blank=True, help_text='e.g. 17:00–19:00', max_length=100)),
                ('slots_per_day', models.IntegerField(default=20)),
                ('prefix', models.CharField(help_text='Token prefix e.g. A, B, C', max_length=5, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on-leave', 'On Leave')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='admin_panel.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('max_patients', models.IntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='admin_panel.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
