# Generated by Django 6.0.5 on 2026-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0002_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='disabled_slots',
            field=models.TextField(blank=True, default='', help_text='Comma-separated HH:MM times hidden from slot grid'),
        ),
    ]
