# Generated by Django 6.0.5 on 2026-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0004_rename_slot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='night_slots',
            field=models.CharField(blank=True, help_text='e.g. 21:00–23:00', max_length=100),
        ),
    ]
