# Generated by Django 6.0.5 on 2026-06-28 06:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_admin', '0001_initial'),
        ('reception', '0003_alter_queueentry_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('prescription', models.TextField(blank=True, default='')),
                ('is_visible_to_patient', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_note', to='reception.queueentry')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='info', max_length=30)),
                ('icon', models.CharField(blank=True, default='ti-info-circle', max_length=50)),
                ('icon_class', models.CharField(blank=True, default='ni-blue', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hospital_admin.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.IntegerField(default=10, help_text='Minutes per consultation slot')),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('break_time', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('auto_advance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='hospital_admin.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(blank=True, default='', max_length=20)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('rbs', models.IntegerField(blank=True, null=True, verbose_name='RBS / Blood sugar (mg/dL)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_records', to='reception.queueentry')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
